### ISSUE TITLE
Both cli clients use the same port

### ISSUE THREAD

**Issue by jbroudou** [handshake-org/hs-client#8]
Requests to hsw and hsd RPC endpoints are done over different ports. However both hsd-cli and hsw-cli use the same environment variable "http-port" which means that you can't use the client on the same machine to issue requests to both endpoints.

Ideally they should look at differently named environment variables.

**Comment by tynes** [comment]
I see where you are coming from, the code is in the CLI constructors where the config is created.

https://github.com/handshake-org/hs-client/blob/0299baf7b3ec26d003b17aa43457965a234a638d/bin/hsw-cli#L18

Since for both hsw-cli and hsd-cli they are both `hsd`, the same environment variables will apply to both. It is possible though to issue requests from the same terminal without having the environment variables collide

```bash
$ HSD_HTTP_PORT=14037 ./bin/hsd-cli info
```

```bash
$ HSD_HTTP_PORT=14039 ./bin/hsw-cli get
```

You can also use `--network` which will handle using the standard ports for each network correctly.
It may be easier to use a config file with the `--config` flag if you have many configuration options

**Comment by jbroudou** [comment]
Great. I was trying to avoid a config file option, but specifying the port on the command line works for my use case.
